spring.application.name=SpringbootHRMS04


# =======================
	# APPLICATION
	# =======================
	
	server.port=8080
	
	# =======================
	# DATABASE CONFIG (MySQL)
	# =======================
	spring.datasource.url=jdbc:mysql://localhost:3306/springboothrms04
	spring.datasource.username=root
	spring.datasource.password=Prajwal@09062003
	spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
	
	# =======================
	# JPA / HIBERNATE
	# =======================
	spring.jpa.hibernate.ddl-auto=update
	spring.jpa.show-sql=true
	spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
	
	# =======================
	# OPENAI CONFIG
	# =======================
	
	#openai.api.key=${OPENAI_API_KEY}
	#openai.api.url=https://api.openai.com/v1/responses
	#openai.model=gpt-4o-mini
	
	sarvam.api.key=YOUR_SARVAM_API_KEY
	
	
	# =======================
	# LOGGING (OPTIONAL)
	# =======================
	logging.level.org.springframework=INFO
	logging.level.com.kodnest.project=DEBUG